### ISSUE TITLE
x-opbeat-client header forces OPTIONS requests

### ISSUE THREAD

**Issue by broofa** [opbeat/opbeat-js-core#9]
Because `x-opbeat-client` is not a [simple header](https://www.w3.org/TR/cors/#simple-header), the browser makes an additional OPTIONS request before each POST to `.../transactions` as part of the CORS handshaking.  (See screenshot below).

This doubles the number of network requests unnecessarily. (x-opbeat-client's info could pretty easily be passed as a query param or property of the request body.)

The double request thing causes pain for our customers by increasing their bandwidth burden.
It causes pain for us (as developers) by cluttering up the developer tools console and network panel.  And it causes pain for OpBeat by creating extra traffic for your servers and extra log entries.

![image](https://user-images.githubusercontent.com/164050/30930067-56a43a32-a375-11e7-9e6f-3dac4ab97138.png)

**Comment by hmdhk** [comment]
Thanks for pointing that out @broofa ,

We have considered removing `x-opbeat-client` header however we haven't been able to so yet since Opbeat API relies on this header.
I will make sure that we reconsider this for our future releases.

Cheers
